# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Huong Do
# tagline:          'A Jekyll theme'
description:      'Information and Service Management M.Sc. student at Aalto University'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Huong Do'
  url:            https://www.linkedin.com/in/huong-do-4962346b/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/huongdo108
  
linkedin:
  repo:           https://www.linkedin.com/in/huong-do-4962346b/
  
certificate1:
  repo:           https://github.com/huongdo108/ETL-pipeline-US-immigration-Pyspark-Airflow-AWS/blob/master/Udacity_data_engineering_nanodegree_certificate.PNG
  
certificate2:
  repo:           https://www.datacamp.com/statement-of-accomplishment/track/95c744d9c9addbe70d10a0d3070ed7b2893ee85b
